### ISSUE TITLE
配方化

### ISSUE THREAD

**Issue by shinzoqchiuq** [qpng/tyungrua#1]
輸入法文件現在放置在 `ime` 文件夾下，無法使用 [plum](https://github.com/rime/plum) 工具進行安裝和更新。能否把輸入法文件移至頂層目錄呢？

**Comment by qpng** [comment]
你好，我已將輸入法文件移至頂層目錄了。這樣就能使用 plum 了嗎，還是有別的要求？

**Comment by shinzoqchiuq** [comment]
這樣就可以了。
